### ISSUE TITLE
Issue with adding a new element to an existing SVG file.

### ISSUE THREAD

**Issue by khovorka** [huei90/snap.svg.zpd#26]
This is a follow-up as the last issue was closed for whatever reason.
I have gotten things working more completely, however, there is an
issue that once I load a svg file I can now edit the graphics on it that
currently exist. However, if I add a new element then all the old elements
get locked and so I can't edit them any further. I can only edit the new elements.
I need to know how to allow editing of all elements in this situation.

There is a follow up to that in that I would like to lock just a couple elements
so they are not moveable, but, remain clickable to allow some editing.

I do appreciate any help on this.  
Not trying to be a pain but need some help with this working.

Kim H.

**Comment by khovorka** [comment]
Ok, I just need to know how to lock an element so that it can not be moved such as a specific rect
or circle.

**Comment by khovorka** [comment]
Just to clarify, what I mean by not move is that I can't drag it other than zoom in and out and also pan, but, that is it.

Thanks

**Comment by tikiatua** [comment]
Hi @khovorka ,
this feature is currently not implemented in the library.

**Comment by huei90** [comment]
Hi @khovorka 
As we mentioned before, 

"This usually use on present view only. Not for Storing or Modifying the paper."

So there's no possible to do what you need right now.

But I hope we can do it in the near future. :laughing:

**Comment by khovorka** [comment]
Thanks for the response.

So the one other issue is when adding a new element to snap.svg and zooming out is that the
when dragging the element it is way behind the cursor and travels slowly, this gets more distorted the farther out or also the farther in you zoom.

What is a bit surprising is that when I load the save svg file and zoom out the elements follow along with the cursor very quickly and so it looks good in that case.

Thanks again,
Kim H.
