### ISSUE TITLE
Issue with dragging an element

### ISSUE THREAD

**Issue by khovorka** [huei90/snap.svg.zpd#30]
I have been using snap.svg and snap.svg.zpd for not to long a time now 
and can add various elements to my root svg element. That includes
loading other svg elements in to the root svg and so these elements
are svg tags themselves, which appears to be fine. The issue I have is
that I need to be able to drag these svg elements around inside the
root svg element. They do display on the screen fine as stated but I
am not successfully moving them around when then are clicked on.
The code I am using to load the svg files is Snap.load() and perhaps
that is the issue is there a s.load for snap.svg.zpd that I should be using.
I have not discovered it if there is? I am using s.image to load an image file
and I can move it around with the mouse. 

I appreciate any help or example on how to do this properly.

Kim H.

**Comment by huei90** [comment]
hi @khovorka 

How about this?
https://github.com/huei90/snap.svg.zpd/blob/master/index.html#L70

**Comment by huei90** [comment]
Close it. Open if needed.
