### ISSUE TITLE
Using zpd with an external svg

### ISSUE THREAD

**Issue by jonnymaceachern** [huei90/snap.svg.zpd#32]
I'm getting undefined function when I try to use zpd with an external SVG:

		var s = Snap( "#canvas" );
		Snap.load( "svg/example.svg", svg_loaded );

		function svg_loaded( data ){

			// returns 'undefined function'
			s.zpd();

			// ... do stuff
		}

**Comment by tikiatua** [comment]
Hi @jonnymaceachern,

It should work, if you handle it a little bit differently:

```javascript
    var s = Snap( "#canvas" );
    Snap.load( "svg/example.svg", svg_loaded );

    function svg_loaded( data ){

        // select the content inside the svg of the imported file
        var g = data.select('svg');

	// append the imported svg to our canvas
	s.append(g);

        // initialize zpd
        s.zpd();

        // ... do stuff
    }

```
Please let me know if this works for you.

**Comment by jonnymaceachern** [comment]
No luck. I checked the network tab and both libs are being loaded fine.

It's rendering the svg and I'm able to manipulate it with Snap, though I'm still getting undefined function when calling `.zpd()` on my Snap object. I'm going to test it with a less complex svg and create a repo that you can look at if that doesn't work.

**Comment by tikiatua** [comment]
This issue usually occurs if the element passed to the Snap function is not an svg-element.

So your html should look like this:
```html
<body onload="loadExternalSvg">
  <svg id="canvas"></svg>
</body>
```

And in your javascript you could then to something like this:
```javascript
var loadExternalSvg = function() {

  // make sure that canvas is an svg element
  // you should actually not use the term canvas at it might
  // easily be mistaken for a canvas-element
  var s = Snap( "svg#canvas" );
  Snap.load( "svg/example.svg", svg_loaded );

  function svg_loaded( data ){

    // append the imported svg to our canvas
    s.append(data);

    // initialize zpd
    s.zpd();

    // ... do stuff
  }

}
```

**Comment by jonnymaceachern** [comment]
Bingo! I was using `<div id="canvas"></div>` rather than `<svg id="canvas"></svg>`.

Thanks @tikiatua
