### ISSUE TITLE
'destroy' doesn't work correctly in Internet Explorer (Solution provided)

### ISSUE THREAD

**Issue by greglbd** [huei90/snap.svg.zpd#36]
When you use destroy in IE it doesn't remove the zpd.

this isn't a huge problem for most users but i discovered it as i need to destroy and immediately re load the zpd and it just takes the children from the original zpd and puts them inside a nested zpd which has the same ID.

    <zpd id="my-zpd-uuid">
        <zpd  id="my-zpd-uuid">
             ...child nodes
        </zpd>
    </zpd>

the reason this happens is because internet explorer doesn't understand parentElement in the _removeNodeKeepChildren function.  I discovered a fix, replace parentElement with parentNode which is below.

    /**
     * remove node parent but keep children
     */
    var _removeNodeKeepChildren = function removeNodeKeepChildren(node) {
      if (!node.parentNode) {
        return;
      }
      while (node.firstChild) {
        node.parentNode.insertBefore(node.firstChild, node);
      }
      node.parentNode.removeChild(node);
    };

cheers

Greg

**Comment by huei90** [comment]
Hi @greglbd 
Great suggestion!

I wish to get your PR for this fix.

Would you like to help me on this? :beers:

**Comment by huei90** [comment]
nudge @greglbd

**Comment by greglbd** [comment]
@huei90 https://github.com/huei90/snap.svg.zpd/pull/39 for some reason it creates merge conflicts on your repo, if i do the pr in ligools repo then it's fine....

**Comment by huei90** [comment]
@greglbd Sorry for the late reply. I have just updated the code! Please check it.

**Comment by greglbd** [comment]
@huei90 looks good to me, works now :)

**Comment by huei90** [comment]
Good
