### ISSUE TITLE
Drawing over existing paper not being displaced.

### ISSUE THREAD

**Issue by GAZ082** [huei90/snap.svg.zpd#38]
Hi guys. I created a paper and loaded and external svg. Applied the plugin, works great.

Now, if i try to draw something on the paper, two things:

1. does not respect the paper's coordinates.
2. When panning, the new element does not follows the loaded SVG.

I bet 1 and 2 are related. Perhaps i'm missing something and i'm not implementing correctly the plugin.

**Comment by huei90** [comment]
You need to reapply the plugin.

**Comment by tikiatua** [comment]
Hi @GAZ082,

the plugin works by putting all elements in your svg into a separate group (a g-element) and applying all transformations to the elements in this group.

Hence it should work as expected if you add the new elements to the zpd group instead of the svg-element

![zpd_explanation](https://cloud.githubusercontent.com/assets/1379175/7153178/13c0363e-e348-11e4-8fa6-89b1415e3c5f.png)

**Comment by huei90** [comment]
cool @tikiatua ! Your graph is very understandable and clear.

Seems this question is already being asked for several times.
Should we add this graph to the README?

**Comment by tikiatua** [comment]
Hi @huei90, thanks for the praise - and good idea.
It would probably help people to understand the inner working of the plugin a little better.

**Comment by huei90** [comment]
@tikiatua 
Help yourself to highlight them :smile:

**Comment by GAZ082** [comment]
Why this is not working then. The only way i found to make it work is loading zpd inside the onSVGload function:

var paper = Snap('#svg');
var image = Snap.load("image.svg", onSVGloaded);
function onSVGloaded(data) {
    paper.append(data);
}
paper.zpd();

This works:

var paper = Snap('#svg');
var image = Snap.load("image.svg", onSVGloaded);
function onSVGloaded(data) {
    paper.append(data);
    paper.zpd();
}

**Comment by huei90** [comment]
`Snap.load` is ajax call,
you should use the third example you gave.

**Comment by GAZ082** [comment]
Mmm, thank you. Now I'll go to annoy the Google Groups with a question related to this. Hehe.

Issue closed!

**Comment by huei90** [comment]
:beers:
