### ISSUE TITLE
How to dynamically scale and/or rotate an SVG image element

### ISSUE THREAD

**Issue by khovorka** [huei90/snap.svg.zpd#40]
Hello,

I want to try and make this clear to understand hopefully not lengthy.
What I need to do is to select and SVG element (say a rect) with the mouse and without
knowing what type of svg element it is to scale or rotate the selected element in place.
I can use jQuery to get the element Id or class and that helps me to know if I have say
a rect or an image element. I will mostly work with image elements in this case. So I
need to then know how to I guess clone the image element with snap.svg or use the existing
element in snap to rotate and/or scale the size of the image using a transform. I am not
having success with this. If anyone would be will to share code on how to dynamically do that
for an SVG element I would be thankful. The other issue with this would be that I will be opening
exising SVG files and need to do the rotating and scaling. Just another consideration why this
needs to be dynamic.

Thank you all.
Kim

**Comment by huei90** [comment]
@khovorka snap.svg.zpd covers on zpd (zoom-pan-drag).

on the scale/rotate, I'm afraid that zpd can't provide you this kind of function.

But some days we might need it, and will become snap.vg.zpdsr (some kind like this XDDD)

**Comment by huei90** [comment]
Close it. Open if needed.
