### ISSUE TITLE
documentation on point conversion misleading

### ISSUE THREAD

**Issue by justin-hackin** [huei90/snap.svg.zpd#41]
The formula for converting a point at the end of the readme is misleading in that it doesn't take into account any rotation that may be applied to the matrix.  I think it would be better to at least clarify this, but even better, include the true matrix calculation formula as such:

```
// where mat is SVGTransform matrix obtained by paper.zpd('save') and pt is [x,y]
function pointThroughMatrix(mat, pt){
    x = mat.a*pt[0] + mat.c*pt[1] + mat.e ;
    y = mat.b*pt[0] + mat.d*pt[1] + mat.f;
    return [x,y];
}
```

**Comment by huei90** [comment]
Hi @justin-hackin Sorry for the misleading. Would you mind give me a PR to update the documentation for this point?

**Comment by huei90** [comment]
Hi @justin-hackin Any update from this?
