### ISSUE TITLE
scroll-zoom does not respect mouse position on absolutely positioned svg documents 

### ISSUE THREAD

**Issue by justin-hackin** [huei90/snap.svg.zpd#44]
Add the following code after application of zpd in demo to observe this bug:
```
paper.attr('style', "postion:absolute; top:300px; left:300px");
```

**Comment by justin-hackin** [comment]
See the following commit for a fix : https://github.com/justin-hackin/snap.svg.zpd/commit/52514e4d6ec43e7802496cd7f755128a4b698555

**Comment by justin-hackin** [comment]
actually, that doesn't work unless the svg has the top/left, this seems to work better: https://github.com/justin-hackin/snap.svg.zpd/commit/b78ca41d51829a3f08c8cd649e31c3206634a97e

**Comment by huei90** [comment]
I don't get it. Would you mind explain more about this?

**Comment by mvd366** [comment]
Currently, the getEventPoint function assumes that the parent of zpdElement is located at (0,0). @justin-hackin b78ca41 fixes this by recursively looping through all parent elements to calculate the global offset of the SVG from the origin.

**Comment by huei90** [comment]
Hi @justin-hackin @mvd366 I have added these code. Thanks :beers:
