### ISSUE TITLE
Zooming problem

### ISSUE THREAD

**Issue by jay-cz** [huei90/snap.svg.zpd#47]
I have came across quite odd situation. When I add SVG element in the container somewhere in the web page zooming in and out does not work properly. When I set absolute positioning of SVG element having it in the left and top most corner of the browser window (left: 0; top: 0) everything works as it should.

The problem also persist in all plugins DEMO pages - when you add some top-margin to the svg elements on the page, you will see what I mean when you zoom in / out.

Is there any workaround or is this behaviour fixed in new beta version?

**Comment by tikiatua** [comment]
Hi Lukas,

the beta version is handling svg-elements with «variable size» (i.e. in responsive elements) in a different way and might thus work better. However, there are a few functions in the regular branch that have not yet been integrated in the beta branch.

**Comment by jay-cz** [comment]
Hi Tikiauta,

thanks, I will check it out.

**Comment by jay-cz** [comment]
Hi again, thanks for the support. I used beta version and everything works as it should. I am looking forward to full version! :)

**Comment by huei90** [comment]
Thanks. =)
