### ISSUE TITLE
Zoom event with mouseWheel

### ISSUE THREAD

**Issue by jbajou** [huei90/snap.svg.zpd#48]
Hello,

is there any way to retrieve the zoom coefficient on mouseWheel ? Or, in other terms, is there any way to attach an event listener to be called on each zoom (from call to zoomTo or mouseWheel action) ?

Thanks in advance,

Regards,

**Comment by tikiatua** [comment]
Hi @jbajou,

The current structure of snap.svg.zpd is not set up to support this. I have though been planning a rewrite of the plugin to an event based architecture which would allow us to a) listen to the events raised by the plugin an b) trigger zoom and drag events with custom code (i.e. using hammer.js to support touch devices).

Unfortunately, I cannot give you an ETA for this new version and there might well be some performance issues.

**Comment by tikiatua** [comment]
We could use the eve library – included with snap.svg – as event bus or try creating our own. 

Documentation on eve is available in the raphaeljs documentation (the precursor of snap.svg)
http://raphaeljs.com/reference.html#eve

**Comment by jbajou** [comment]
Hello,

Thanks for your feedback. That's what I understood from the code, but I wanted to be sure.

Love the idea and would be happy to help though. Get in touch when you start if needed.
