### ISSUE TITLE
Convert SVG Click Location to Coordinates within 

### ISSUE THREAD

**Issue by cjgordon** [huei90/snap.svg.zpd#50]
Hi,
I'm trying to do something pretty basic but, think I'm either being a noob or missing a trick.

I have an SVG with ZDP activated, when a click click occurs on the SVG I wan't to draw a circle at the mouses x and y coordinates. What I have so far is pretty straight forward, it takes the mouses screen coordinates, and SVG's position offsets to calculate mouse location with the SVG. 

I have tried a bunch of ways of trying to do this but all of them end up with the circle being drawn offset by varying amounts (depending on zoom and pan) from the actual cursor location.

Any ideas would be much appreciated.

Cheers
Chris

**Comment by huei90** [comment]
@cjgordon Have you tried using `paper.zpd('toggle')` while drawing?

https://github.com/huei90/snap.svg.zpd/pull/42

**Comment by tikiatua** [comment]
Hi @cjgordon,

this is actually more tricky then it seems in the beginning. The svg element might have some transformation applied to it (i.e. using viewport and viewbox transformations) and zpd will also create a group that applies itself some transformation to the containing elements (i.e. using scale, rotate and translate transformations).

When you draw a point with your mouse, you must translate the position of this point into the svg and zpd translation space, otherwise it will always appear in the wrong spot. Thus you will find yourself in the area of matrix transformations, which can rapidly get a little bit complicated (you might find some help in the code in the beta branch on how to handle this).

**Comment by cjgordon** [comment]
Wow, thanks for speedy replies! @tikiatua that amazing world of matrix hurt is exactly where I'm at!

I'll take a look at beta branch and report my findings if I work this one out. Interesting I used to do this in Raphael with the old Raphael ZPD plugin, I'll try dig up that code, maybe the same principles apply.

**Comment by cjgordon** [comment]
BOOM. This is why we git. :) Dug through the depths of my git repo's and found my old implementation of similar function in Raphael: 

 
    Raphael.fn.cursorPoint = function(evt){
      var svg = document.getElementsByTagName("svg")[0]
      svg = document.querySelector('svg');
      var pt = svg.createSVGPoint();
      pt.x = evt.clientX; 
      pt.y = evt.clientY;
      return pt.matrixTransform(svg.getScreenCTM().inverse());
     };

Now that used to work because the old ZPD plugin for Raphael used the viewBox  attribute to apply transform to whole paper whereas this awesome new shiny one applies a transform to a G element so I had to change it a bit but basically this now works. 
    

            // drawing-paper is id of my SVG with ZPD applied.
		$("#drawing-paper").click( function (event) {
			// Get coords of click minus the offsets due to CSS positioning of SVG such as margins
			var x = event.clientX - $("#editor-paper").offset().left;
			var y = event.clientY - $("#editor-paper").offset().top;

			// Get the current ZPD transfrom matrix
			var zpdMAtrix = editorPaper.zpd('save');

			// create SVG point with x,y
			var screenPoint = svg.createSVGPoint();
			screenPoint.x = x;
		    screenPoint.y = y;

		    // Use inverse matrix of ZPD transform a apply matrix transfrom to click location point.
		    var actualPt = screenPoint.matrixTransform(zpdMAtrix.inverse());

		    // Draw circle/shape/dragon/whatever
			var ele = editorPaper.circle(actualPt.x, actualPt.y, 10).attr({fill:"red"});

			// Add to ZPD group
			var canvas = Snap.select('#snapsvg-zpd-'+editorPaper.id);
			canvas.add(ele);

			// PROFIT
		});

Thanks for help!

**Comment by cjgordon** [comment]
BOOM. This is why we git. :) Dug through the depths of my git repo's and found my old implementation of similar function in Raphael: 

 
    Raphael.fn.cursorPoint = function(evt){
      var svg = document.getElementsByTagName("svg")[0]
      svg = document.querySelector('svg');
      var pt = svg.createSVGPoint();
      pt.x = evt.clientX; 
      pt.y = evt.clientY;
      return pt.matrixTransform(svg.getScreenCTM().inverse());
     };

Now that used to work because the old ZPD plugin for Raphael used the viewBox  attribute to apply transform to whole paper whereas this awesome new shiny one applies a transform to a G element so I had to change it a bit but basically this now works. 
    

            // drawing-paper is id of my SVG with ZPD applied.
		$("#drawing-paper").click( function (event) {
			// Get coords of click minus the offsets due to CSS positioning of SVG such as margins
			var x = event.clientX - $("#editor-paper").offset().left;
			var y = event.clientY - $("#editor-paper").offset().top;

			// Get the current ZPD transfrom matrix
			var zpdMAtrix = editorPaper.zpd('save');

			// create SVG point with x,y
			var screenPoint = svg.createSVGPoint();
			screenPoint.x = x;
		    screenPoint.y = y;

		    // Use inverse matrix of ZPD transform a apply matrix transfrom to click location point.
		    var actualPt = screenPoint.matrixTransform(zpdMAtrix.inverse());

		    // Draw circle/shape/dragon/whatever
			var ele = editorPaper.circle(actualPt.x, actualPt.y, 10).attr({fill:"red"});

			// Add to ZPD group
			var canvas = Snap.select('#snapsvg-zpd-'+editorPaper.id);
			canvas.add(ele);

			// PROFIT
		});

Thanks for help!
