### ISSUE TITLE
Specify license in README

### ISSUE THREAD

**Issue by jaapz** [huei90/snap.svg.zpd#52]
Source code says the plugin is BSD licensed. Would be nice to mention that in the README as well.

**Comment by huei90** [comment]
:+1: I will do it. Or you want to help? create a LICENSE.md file

**Comment by huei90** [comment]
Sorry for the late .

License is here.
https://github.com/huei90/snap.svg.zpd/commit/ef60a8bceceee210c6e3821912ad388bb6c88b74
