### ISSUE TITLE
Zoom and Pan at the same time?

### ISSUE THREAD

**Issue by nathanedwards** [huei90/snap.svg.zpd#53]
Apologies if this is really obvious or the wrong place to ask - but I've been struggling for the last few minutes on zooming and panning at the same time.  It's a simple concept, let's take http://huei90.github.io/snap.svg.zpd/demo2.html as an example.

Currently you can zoom on a point with your mouse wheel, but I want to be able to click on a country and have it zoom to that country.  

if I use zoomTo it's just going to an arbitrary point.  Using panTo at the same time doesn't work.

I am assuming you could set a new 'center' of the zoom before zoomTo happens?

**Comment by huei90** [comment]
There is no way we can perform Zoom and Pan at the same time.

In your case, you need zoomTo.

In beta v0.1 version, you can try the zoomTo feature.

https://github.com/huei90/snap.svg.zpd/tree/beta_v0.1.0
