### ISSUE TITLE
'SVGElement.offsetParent' is deprecated

### ISSUE THREAD

**Issue by yangpu** [huei90/snap.svg.zpd#58]
This warning has been printed on chrome 48.

`
'SVGElement.offsetParent' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
`

**Comment by astroK8** [comment]
I have test with getBoundingClientRect as recommended by google, it seems to do the trick. 
_findPos method should be modified as follow:
        var _findPos = function findPos(obj) {
           var curleft = curtop = 0;
	   var boundingClientRect = obj.getBoundingClientRect();
           if (boundingClientRect) {
			   curleft=boundingClientRect.left;
			   curtop=boundingClientRect.top;
           }
           return [curleft,curtop];
};

**Comment by huei90** [comment]
@yangpu Thanks for your report.
@astroK8 Do you want to create a PR to fix this?

**Comment by astroK8** [comment]
Yes i will.

**Comment by huei90** [comment]
Thanks @astroK8

**Comment by huei90** [comment]
Fixed.
