### ISSUE TITLE
zoom on SVG document with offset position

### ISSUE THREAD

**Issue by mitjajez** [huei90/snap.svg.zpd#62]
Can i pass offset position of SVG document to zpd events?

Or could Snap handle this?

my event.pageX in not the same as X of SVG, this effect that zoom point is not on mouse but on the right for this offset.x

I use it on https://github.com/mitjajez/SONCE/

**Comment by tikiatua** [comment]
Hi mitjajez,

Unfortunately this is currently not possible, as the scope of the library is very narrow and it was not intended to be used when editing svg documents.

You may very well fork the code and try to add some custom offset yourself.
