### ISSUE TITLE
 bower install snap.svg.zpd --save installs old version

### ISSUE THREAD

**Issue by toolchild** [huei90/snap.svg.zpd#66]
Hi,

when i use  `bower install snap.svg.zpd --save` to install this plugin I get code still using `obj.offsetParent` to figure out the point where the mouseevent occured for zooming.

```
 var _findPos = function findPos(obj) {
           var curleft = curtop = 0;
           if (obj.offsetParent) {
               do {
                   curleft += obj.offsetLeft;
                   curtop += obj.offsetTop;
               } while(obj = obj.offsetParent);
           }
           return [curleft,curtop];
        };
```

This does return undefined in my usecase and therefore zooming is calculated to absolute coordinates and not to relative element coordinates.

I have never used bower before, so this might be expected behavior. If it is, what must i do to get the version here on github via console using bower?

**Comment by huei90** [comment]
Can you check which version are you using now? the latest version is `0.11`

**Comment by toolchild** [comment]
`bower install snap.svg.zpd --save`
returns
```
bower snap.svg.zpd#*            cached https://github.com/huei90/snap.svg.zpd.git#0.0.11
bower snap.svg.zpd#*          validate 0.0.11 against https://github.com/huei90/snap.svg.zpd.git#*
bower snap.svg.zpd#^0.0.11     install snap.svg.zpd#0.0.11
bower                          no-json No bower.json file to save to, use bower init to create one
```

containing this method:


```
/**
         * Instance an SVGPoint object with given event coordinates.
         */
         var _findPos = function findPos(obj) {
           var curleft = curtop = 0;
           if (obj.offsetParent) {
               do {
                   curleft += obj.offsetLeft;
                   curtop += obj.offsetTop;
               } while(obj = obj.offsetParent);
           }
           return [curleft,curtop];
        };
```

So yes, it is `0.11` but what I need would be the version that uses this method. 

```
/**
         * Instance an SVGPoint object with given event coordinates.
         */
        var _findPos = function findPos(obj) {
          var curleft = curtop = 0;
          var boundingClientRect = obj.getBoundingClientRect();
          if (boundingClientRect) {
            curleft = boundingClientRect.left;
            curtop = boundingClientRect.top;
          }
          return [curleft, curtop];
          return [curleft, curtop];
        };
```

So it seems to be that bower is serving a version that has different code than the file available on github. For my purposes `0.11` does not work. Commit 3891737 on github does work.

Thanks for the quick reply.

**Comment by huei90** [comment]
Hello @toolchild 

yes, what you can do for now, is pulling the latest commit of the repo. 
The latest code is not on the version tag now.

**Comment by toolchild** [comment]
Hi again,

Just for completeness sake:
Adding the following dependency to the `bower.json` gives me the correct version.

```
"dependencies": {
    "snap.svg.zpd": "https://github.com/huei90/snap.svg.zpd.git#fee6d6025e736945a3cd2828b2d02b9287856b12"
  },
```

**Comment by huei90** [comment]
Yes this is what you can do for now. 

I will update you once there is a bump version 😄
