### ISSUE TITLE
load: not working

### ISSUE THREAD

**Issue by rgruesbeck** [huei90/snap.svg.zpd#68]
I can't seem to get paper.zpd({ load: svgMatrix }) to work
paper.zpd('save') works fine

**Comment by huei90** [comment]
Is there any error message when using `load`?

**Comment by rgruesbeck** [comment]
there is no error, and no effect
here is what I tried

const matrix = {a: 2, b: 0, c: 0, d: 1, e:0, f:0};
this.paper.zpd({                                  
  load: matrix                                    
});

**Comment by rgruesbeck** [comment]
``

**Comment by huei90** [comment]
Interesting. Can you tell me which browser are you using?

**Comment by rgruesbeck** [comment]
Chorme, also tried this in Firefox with no error

**Comment by huei90** [comment]
`paper.zpd('load')` works only when initialization, doesn't work if you already `paper.zpd()` your svg.

**Comment by rgruesbeck** [comment]
ok thanks
